"""Phase 6A: Post-Listing Observation Model & Deterministic Return Engine package."""

from .models import (
    BenchmarkObservation,
    CalculationMetadata,
    Horizon,
    ObservationStatus,
    PostListingObservation,
    PriceObservation,
    ProvenanceRecord,
    ReturnSet,
    VerificationStatus,
)
from .price_adapter import (
    DailyPriceRecord,
    DuplicatePriceConflictError,
    MalformedPriceDataError,
    NegativePriceError,
    PriceAdapterError,
    PriceDataset,
    load_price_file,
)
from .return_engine import (
    CALCULATION_VERSION,
    build_observation,
    calculate_absolute_return,
    calculate_benchmark_return,
    calculate_excess_return,
    calculate_listing_gain,
    calculate_secondary_return,
    compute_observation_hashes,
    sha256_canonical_dict,
)
from .storage import (
    EvaluationNotFoundError,
    NotFinalEvaluationError,
    ObservationStorageError,
    ResultHashMismatchError,
    get_observations_dir,
    list_observations,
    read_observation,
    save_observation,
    validate_parent_evaluation,
    verify_observation_hashes,
)
from .trading_calendar import (
    compute_target_date,
    format_iso_date,
    is_trading_day,
    parse_iso_date,
    previous_trading_day,
    resolve_observation_date,
)

__all__ = [
    "BenchmarkObservation",
    "CalculationMetadata",
    "DailyPriceRecord",
    "DuplicatePriceConflictError",
    "EvaluationNotFoundError",
    "Horizon",
    "MalformedPriceDataError",
    "NegativePriceError",
    "NotFinalEvaluationError",
    "ObservationStatus",
    "ObservationStorageError",
    "PostListingObservation",
    "PriceAdapterError",
    "PriceDataset",
    "PriceObservation",
    "ProvenanceRecord",
    "ResultHashMismatchError",
    "ReturnSet",
    "VerificationStatus",
    "CALCULATION_VERSION",
    "build_observation",
    "calculate_absolute_return",
    "calculate_benchmark_return",
    "calculate_excess_return",
    "calculate_listing_gain",
    "calculate_secondary_return",
    "compute_observation_hashes",
    "compute_target_date",
    "format_iso_date",
    "get_observations_dir",
    "is_trading_day",
    "list_observations",
    "load_price_file",
    "parse_iso_date",
    "previous_trading_day",
    "read_observation",
    "resolve_observation_date",
    "save_observation",
    "sha256_canonical_dict",
    "validate_parent_evaluation",
    "verify_observation_hashes",
]
